server:
  port: 8888
  
spring:
  cloud:
    config:
      fail-fast: false
      discovery.enabled: false
      uri: http://config-server:8888
      server:
        git:
          uri: https://github.com/ramirescorreia/spring-cloud-challenge-config.git
          force-pull: true
          cloneOnStart: true
          skipSslValidation: true
          default-label: main
           
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka