spring:
  application:
    name: eats-monolito
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: optional:configserver:http://localhost:8888/
  datasource:
    url: jdbc:h2:mem:mydbapplication
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    properties:
      hibernate:
        connection:
          charSet: UTF-8
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.H2Dialect
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka