spring:
  config:
    import: configserver:http://host.docker.internal:8888
  cloud:
    config:
      enabled: true
  application:
    name: eats-monolito
  profiles:
    active: native
    config:
      uri: http://config-server:8888