spring:
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
  application:
    name: eats-distancia-service
  profiles:
    active: default
    config:
      uri: http://localhost:8888