spring:
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      enabled: true
  application:
    name: eats-distancia-service
  profiles:
    active: default
    config:
      uri: http://config-server:8888
    
eureka:
  instance:
    prefer-ip-address: true