server:
  port: 9080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: login
        uri: http://localhost:9080/login
        predicates:
        - Path=/login/**
      - id: pedidos
        uri: lb://pedidos
        predicates:
        - Path=/pedidos/**
      - id: tipos-de-cozinha
        uri: lb://tipos-de-cozinha
        predicates:
        - Path=/tipos-de-cozinha/**  
      - id: admin
        uri: lb://admin
        predicates:
        - Path=/admin/**
      - id: formas-de-pagamento
        uri: lb://formas-de-pagamento
        predicates:
        - Path=/formas-de-pagamento/**     
      - id: user
        uri: lb://user
        predicates:
        - Path=/user/**
      - id: pagamentos
        uri: lb://pagamentos
        predicates:
        - Path=/pagamentos/**
      - id: parceiros
        uri: lb://parceiros
        predicates:
        - Path=/parceiros/**    
      - id: login
        uri: lb://login
        predicates:
        - Path=/login/**    
zuul:
  ignoredPatterns: /eats-auth/**
  
security: 
  oauth2: 
    resource: 
      user-info-uri: http://localhost:8088/user
      
 